- ui_automation_tests/conftest.py
- ui_automation_tests/features/add_goods.feature
- ui_automation_tests/features/case_notes.feature
- ui_automation_tests/features/flags.feature
- ui_automation_tests/features/organisation_setup.feature
- ui_automation_tests/features/queues.feature
- ui_automation_tests/features/roles.feature
- ui_automation_tests/features/submit_application.feature
- ui_automation_tests/features/teams.feature
- ui_automation_tests/step_defs/flags_test.py
* Improving test data so that the site doesnt get spammed with ''aaaaa' 'test data' etc etc
> improve test data

- ui_automation_tests/step_defs/test_view_case_details.py
https://uktrade.atlassian.net/browse/LT-1567 this bug
> test: comment out tests due to bug

- .gitmodules
Reverts uktrade/lite-internal-frontend#151
> Revert "fix: Change submodule URLs to HTTPS."

- ui_automation_tests/conftest.py
- ui_automation_tests/features/add_goods.feature
- ui_automation_tests/pages/application_page.py
- ui_automation_tests/pages/shared.py
- ui_automation_tests/step_defs/test_goods_clc_query_case.py
> test: click good

- pipeline/Jenkinsfile
Add slack notifications to jenkins file so that lite-builds channel is notified of any test passes or failures.
> test: Add slack notifications to jenkins file

- picklists/views.py
> Ensure letter templates are valid Django templates.

- Procfile
- conf/settings.py
- conf/wsgi.py
* Static assets now show on environments with DEBUG set to False.
> fix: Static assets with Whitenoise

- ui_automation_tests/features/organisation.feature
- ui_automation_tests/step_defs/test_organisation.py
Fix:
Change to lite forms so that user can create organisation
Test:
Change the test so it actually tests that organisation is registered.
> fix: Create organisation fix

- Pipfile
- Pipfile.lock
- README.md
- ui_automation_tests/docker-entry.sh
- ui_automation_tests/e2e.txt
- ui_automation_tests/features/hmrc_query.feature
- ui_automation_tests/selenium-automation-run/Dockerfile
- ui_automation_tests/step_defs/test_hmrc_query.py
Automatically re run any failing tests once.
> Re run failures

- docker-compose.yml
refactor: service to use port 8200 in local docker-compose
> refactor: service to use port 8200 in local docker-compose

- ui_automation_tests/features/teams.feature
- ui_automation_tests/step_defs/test_teams.py
Lite-content is there because i checked out master to get the latest lite-content
> test: Put teams test back

- templates/case/open-licence-case.html
- templates/case/views/standard-goods.html
* Added table columns to indicate if standard/open goods are incorporated or not
> feat: LT-1239 - Incorporated application

- ui_automation_tests/conftest.py
Failing test, a merge conflict must have gone wrong.
> hotfix: Fix flags test

- templates/case/applications/open-licence-case.html
- templates/case/applications/standard-licence-case.html
- templates/case/queries/hmrc-case.html
* Adds numbers next to each good on each applicable case type (standard, open and HMRC)
> feat: LT-1961 - Goods table numbers

- ui_automation_tests/conftest.py
- ui_automation_tests/features/assign_case_flags_to_case.feature
- ui_automation_tests/features/assign_users_to_queue.feature
- ui_automation_tests/features/case_notes.feature
- ui_automation_tests/features/documents.feature
- ui_automation_tests/features/ecju_queries.feature
- ui_automation_tests/features/eua_queries.feature
- ui_automation_tests/features/exhibition_clearance.feature
- ui_automation_tests/features/filter_and_sort_cases.feature
- ui_automation_tests/features/flags.feature
- ui_automation_tests/features/generated_documents.feature
- ui_automation_tests/features/give_advice.feature
- ui_automation_tests/features/goods_clc_query_case.feature
- ui_automation_tests/features/hmrc_query.feature
- ui_automation_tests/features/letter_templates.feature
- ui_automation_tests/features/manage_cases.feature
- ui_automation_tests/features/organisation.feature
- ui_automation_tests/features/picklists.feature
- ui_automation_tests/features/queues.feature
- ui_automation_tests/features/roles.feature
- ui_automation_tests/features/teams.feature
- ui_automation_tests/features/view_case_details.feature
- ui_automation_tests/step_defs/test_exhibition_clearance.py
- ui_automation_tests/step_defs/test_filter_and_sort_cases.py
- ui_automation_tests/step_defs/test_goods_queries.py
- ui_automation_tests/step_defs/test_view_case_details.py
* Only go to internal homepage when needed for test speed improvements
* Tidy up signing into SSO on each test to decouple it from being a fixsture on going to the homepage
* Some further general set up of given steps within tests
> test: Only go to homepage when needed

- ui_automation_tests/conftest.py
- ui_automation_tests/features/assign_case_flags_to_case.feature
- ui_automation_tests/features/case_officer.feature
- ui_automation_tests/features/documents.feature
- ui_automation_tests/features/give_advice.feature
- ui_automation_tests/features/hmrc_query.feature
- ui_automation_tests/features/review_goods.feature
- ui_automation_tests/features/view_case_details.feature
- ui_automation_tests/step_defs/test_hmrc_query.py
* Change test to have a seeded hmrc query.
* some clean up
> test: Seed hmrc query

- ui_automation_tests/conftest.py
- ui_automation_tests/features/assign_case_flags_to_case.feature
- ui_automation_tests/features/case_officer.feature
- ui_automation_tests/features/documents.feature
- ui_automation_tests/features/give_advice.feature
- ui_automation_tests/features/hmrc_query.feature
- ui_automation_tests/features/review_goods.feature
- ui_automation_tests/features/view_case_details.feature
- ui_automation_tests/step_defs/test_hmrc_query.py
This reverts commit fb441fab6ec56469dcad18ae3712920ece6103a0.
> Revert "test: Seed hmrc query"

- conf/constants.py
- core/services.py
- ui_automation_tests/conftest.py
- ui_automation_tests/features/goods_queries.feature
- added two additional states for goods queries - PV review and CLC review
https://uktrade.atlassian.net/browse/LT-2149
> feat: LT-2149 - Add PV Grading and CLC to list of available goods query states

- assets/css/components/_ring.scss
- core/builtins/custom_tags.py
> Design: Update SLA ring colours

- assets/css/components/_all.scss
- assets/css/components/_nav.scss
* Part of this is splitting out the user account styling from shared-assets as internal and exporter will be diverging in the future
> chore: Update SCSS

- manifest.yml
This change is needed to make manifest file compatible with v3 cipipeline
> v3-cipipeline fix

- templates/queues/cases.html
This updates the frontend to match the new keys sent by the API.
> chore: Cases optimisation

- templates/case/includes/parties.html
- only display document links if there are documents (d'oh)
> feat: LT-2270 - Optional document upload 

- cases/views/generate_document.py
- templates/flags/flagging-rules-list.html
- templates/flags/index.html
- templates/includes/pagination.html
- templates/letter-templates/letter-templates.html
- templates/organisations/index.html
- templates/queues/cases.html
- templates/routing-rules/index.html
- templates/users/index.html
* Moves pagination from its HTML page over to a new tag `{% pagination %}`
* Improved design, functionality and accessibility of pagination
* Cuts down on old, duplicated code
> design: Pagination

- cases/forms/generate_document.py
- cases/views/generate_document.py
Fixes a bug where pagination isn't visible on radio button image forms
> fix: Radiobuttons image pagination

- ui_automation_tests/features/view_standard_application.feature
- ui_automation_tests/step_defs/test_view_standard_application.py
Ensure certain tests are in a submitted state to allow them to be edited (may not be if workflow has been applied)
> bugfix: Fix e2e's broken due to routing rules

- Pipfile.lock
- pipeline/Jenkinsfile
* Update to pipfile.lock
* Parallel with three threads to stop docker image crashing
* distribution loadfile so the tests run in a more sensible order
* point submodules to master to fix a bug on advice
> hotfix: Point submodules to master and parallellise better

- ui_automation_tests/conftest.py
- ui_automation_tests/features/assign_case_flags_to_case.feature
- ui_automation_tests/features/assign_users_to_queue.feature
- ui_automation_tests/features/flags.feature
- ui_automation_tests/features/give_advice.feature
- ui_automation_tests/fixtures/add_a_document_template.py
- ui_automation_tests/fixtures/add_a_flag.py
- ui_automation_tests/fixtures/add_a_picklist.py
- ui_automation_tests/fixtures/add_queue.py
- ui_automation_tests/pages/case_page.py
- ui_automation_tests/step_defs/test_assign_users_to_queue.py
- ui_automation_tests/step_defs/test_organisation.py
- ui_automation_tests/step_defs/test_queues.py
- ui_automation_tests/step_defs/test_view_mod_clearance.py
* Making tests run more reliably
* Uncommenting some out that have been commented out for a while.
* Commenting one step out for now until it can be run reliably
> Function to modules

- assets/css/components/snackbar.scss
- templates/queues/cases.html
- ui_automation_tests/pages/case_list_page.py
> chore: Update exporter amendments bar to use snackbar class

- assets/css/components/_flags.scss
- flags/services.py
* Users can now see what flags look like before applying them
> design: Flags

- assets/css/overrides/_table.scss
- core/builtins/custom_tags.py
- templates/case/slices/open-general-licence.html
- templates/case/slices/summary.html
- templates/organisations/organisation/details.html
- templates/organisations/organisation/sites.html
* Adds where the site records are held at
> feat: LT-1409 - OGL cases

- cases/forms/advice.py
- cases/forms/assign_users.py
- cases/forms/move_case.py
- conf/settings.py
- flags/forms.py
- open_general_licences/forms.py
- queues/views.py
- templates/layouts/base.html
- ui_automation_tests/conftest.py
- ui_automation_tests/pages/case_list_page.py
- ui_automation_tests/step_defs/test_additional_contacts.py
- ui_automation_tests/step_defs/test_assign_users_to_queue.py
- ui_automation_tests/step_defs/test_compliance.py
- ui_automation_tests/step_defs/test_ecju_queries.py
- ui_automation_tests/step_defs/test_enforcement.py
- ui_automation_tests/step_defs/test_eua_queries.py
- ui_automation_tests/step_defs/test_filter_cases.py
- ui_automation_tests/step_defs/test_finalise_case.py
- ui_automation_tests/step_defs/test_give_advice.py
- ui_automation_tests/step_defs/test_letter_templates.py
- ui_automation_tests/step_defs/test_manage_cases.py
- ui_automation_tests/step_defs/test_open_general_licences.py
- ui_automation_tests/step_defs/test_review_goods.py
- ui_automation_tests/step_defs/test_view_open_application.py
- ui_automation_tests/step_defs/test_view_standard_application.py
- users/forms/users.py
* Only import javascript the once
* Removed certain imports and replaced with built in functions
> perf: Javascript imports

- assets/css/components/_activity.scss
- cases/forms/advice.py
- cases/forms/assign_users.py
- cases/forms/change_status.py
- cases/forms/done_with_case.py
- cases/forms/move_case.py
- cases/services.py
- cases/urls.py
- cases/views/advice.py
- cases/views/ecju.py
- cases/views/main.py
- flags/forms.py
- queues/services.py
- queues/views.py
- templates/queues/cases.html
- ui_automation_tests/features/assign_users_to_queue.feature
- ui_automation_tests/pages/unassign_queue_page.py
- ui_automation_tests/step_defs/test_assign_users_to_queue.py
- users/services.py
**What's new**
* Added optional note fields for certain actions, such as changing status or assigning users to cases
**Misc**
* _I'm Done_ now extends SingleFormView, errors are handled inline in the form now :)
* _Assign users (queue edition)_ now extends SingleFormView, has a friendly message on success :)
> feat: LT-1188 - I want to have the option to add a note whenever I progress a case
